# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:44:07+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class Bye(BaseModel):
    Season: Optional[int] = None
    Team: Optional[str] = None
    Week: Optional[int] = None


class DepthChart(BaseModel):
    DepthChartID: Optional[int] = None
    DepthOrder: Optional[int] = None
    Name: Optional[str] = None
    PlayerID: Optional[int] = None
    Position: Optional[str] = None
    PositionCategory: Optional[str] = None
    TeamID: Optional[int] = None
    Updated: Optional[str] = None


class News(BaseModel):
    Author: Optional[str] = None
    Categories: Optional[str] = None
    Content: Optional[str] = None
    NewsID: Optional[int] = None
    OriginalSource: Optional[str] = None
    OriginalSourceUrl: Optional[str] = None
    PlayerID: Optional[int] = None
    PlayerID2: Optional[int] = None
    Source: Optional[str] = None
    Team: Optional[str] = None
    Team2: Optional[str] = None
    TeamID: Optional[int] = None
    TeamID2: Optional[int] = None
    TermsOfUse: Optional[str] = None
    TimeAgo: Optional[str] = None
    Title: Optional[str] = None
    Updated: Optional[str] = None
    Url: Optional[str] = None


class Player(BaseModel):
    Active: Optional[bool] = None
    Age: Optional[int] = None
    AverageDraftPosition: Optional[float] = None
    BirthDate: Optional[str] = None
    BirthDateString: Optional[str] = None
    ByeWeek: Optional[int] = None
    College: Optional[str] = None
    CollegeDraftPick: Optional[int] = None
    CollegeDraftRound: Optional[int] = None
    CollegeDraftTeam: Optional[str] = None
    CollegeDraftYear: Optional[int] = None
    CurrentStatus: Optional[str] = None
    CurrentTeam: Optional[str] = None
    DeclaredInactive: Optional[bool] = None
    DepthDisplayOrder: Optional[int] = None
    DepthOrder: Optional[int] = None
    DepthPosition: Optional[str] = None
    DepthPositionCategory: Optional[str] = None
    DraftKingsName: Optional[str] = None
    DraftKingsPlayerID: Optional[int] = None
    Experience: Optional[int] = None
    ExperienceString: Optional[str] = None
    FanDuelName: Optional[str] = None
    FanDuelPlayerID: Optional[int] = None
    FantasyAlarmPlayerID: Optional[int] = None
    FantasyDraftName: Optional[str] = None
    FantasyDraftPlayerID: Optional[int] = None
    FantasyPosition: Optional[str] = None
    FantasyPositionDepthOrder: Optional[int] = None
    FirstName: Optional[str] = None
    GlobalTeamID: Optional[int] = None
    Height: Optional[str] = None
    HeightFeet: Optional[int] = None
    HeightInches: Optional[int] = None
    InjuryBodyPart: Optional[str] = None
    InjuryNotes: Optional[str] = None
    InjuryPractice: Optional[str] = None
    InjuryPracticeDescription: Optional[str] = None
    InjuryStartDate: Optional[str] = None
    InjuryStatus: Optional[str] = None
    IsUndraftedFreeAgent: Optional[bool] = None
    LastName: Optional[str] = None
    Name: Optional[str] = None
    Number: Optional[int] = None
    PhotoUrl: Optional[str] = None
    PlayerID: Optional[int] = None
    Position: Optional[str] = None
    PositionCategory: Optional[str] = None
    RotoWirePlayerID: Optional[int] = None
    RotoworldPlayerID: Optional[int] = None
    ShortName: Optional[str] = None
    SportRadarPlayerID: Optional[str] = None
    SportsDirectPlayerID: Optional[int] = None
    StatsPlayerID: Optional[int] = None
    Status: Optional[str] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    UpcomingDraftKingsSalary: Optional[int] = None
    UpcomingFanDuelSalary: Optional[int] = None
    UpcomingGameOpponent: Optional[str] = None
    UpcomingGameWeek: Optional[int] = None
    UpcomingOpponentPositionRank: Optional[int] = None
    UpcomingOpponentRank: Optional[int] = None
    UpcomingSalary: Optional[int] = None
    UpcomingYahooSalary: Optional[int] = None
    UsaTodayHeadshotNoBackgroundUpdated: Optional[str] = None
    UsaTodayHeadshotNoBackgroundUrl: Optional[str] = None
    UsaTodayHeadshotUpdated: Optional[str] = None
    UsaTodayHeadshotUrl: Optional[str] = None
    UsaTodayPlayerID: Optional[int] = None
    Weight: Optional[int] = None
    XmlTeamPlayerID: Optional[int] = None
    YahooName: Optional[str] = None
    YahooPlayerID: Optional[int] = None


class Referee(BaseModel):
    College: Optional[str] = None
    Experience: Optional[int] = None
    Name: Optional[str] = None
    Number: Optional[int] = None
    Position: Optional[str] = None
    RefereeID: Optional[int] = None


class ScoringDetail(BaseModel):
    GameKey: Optional[str] = None
    Length: Optional[int] = None
    PlayerGameID: Optional[int] = None
    PlayerID: Optional[int] = None
    ScoreID: Optional[int] = None
    ScoringDetailID: Optional[int] = None
    ScoringPlayID: Optional[int] = None
    ScoringType: Optional[str] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    Team: Optional[str] = None
    Week: Optional[int] = None


class Stadium(BaseModel):
    Capacity: Optional[int] = None
    City: Optional[str] = None
    Country: Optional[str] = None
    GeoLat: Optional[float] = None
    GeoLong: Optional[float] = None
    Name: Optional[str] = None
    PlayingSurface: Optional[str] = None
    StadiumID: Optional[int] = None
    State: Optional[str] = None
    Type: Optional[str] = None


class Standing(BaseModel):
    Conference: Optional[str] = None
    ConferenceLosses: Optional[int] = None
    ConferenceRank: Optional[int] = None
    ConferenceTies: Optional[int] = None
    ConferenceWins: Optional[int] = None
    Division: Optional[str] = None
    DivisionLosses: Optional[int] = None
    DivisionRank: Optional[int] = None
    DivisionTies: Optional[int] = None
    DivisionWins: Optional[int] = None
    GlobalTeamID: Optional[int] = None
    Losses: Optional[int] = None
    Name: Optional[str] = None
    NetPoints: Optional[int] = None
    Percentage: Optional[float] = None
    PointsAgainst: Optional[int] = None
    PointsFor: Optional[int] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    Ties: Optional[int] = None
    Touchdowns: Optional[int] = None
    Wins: Optional[int] = None


class Team(BaseModel):
    AverageDraftPosition: Optional[float] = None
    AverageDraftPosition2QB: Optional[float] = None
    AverageDraftPositionDynasty: Optional[float] = None
    AverageDraftPositionPPR: Optional[float] = None
    ByeWeek: Optional[int] = None
    City: Optional[str] = None
    Conference: Optional[str] = None
    DefensiveCoordinator: Optional[str] = None
    DefensiveScheme: Optional[str] = None
    Division: Optional[str] = None
    DraftKingsName: Optional[str] = None
    DraftKingsPlayerID: Optional[int] = None
    FanDuelName: Optional[str] = None
    FanDuelPlayerID: Optional[int] = None
    FantasyDraftName: Optional[str] = None
    FantasyDraftPlayerID: Optional[int] = None
    FullName: Optional[str] = None
    GlobalTeamID: Optional[int] = None
    HeadCoach: Optional[str] = None
    Key: Optional[str] = None
    Name: Optional[str] = None
    OffensiveCoordinator: Optional[str] = None
    OffensiveScheme: Optional[str] = None
    PlayerID: Optional[int] = None
    PrimaryColor: Optional[str] = None
    QuaternaryColor: Optional[str] = None
    SecondaryColor: Optional[str] = None
    SpecialTeamsCoach: Optional[str] = None
    StadiumDetails: Optional[Stadium] = None
    StadiumID: Optional[int] = None
    TeamID: Optional[int] = None
    TertiaryColor: Optional[str] = None
    UpcomingDraftKingsSalary: Optional[int] = None
    UpcomingFanDuelSalary: Optional[int] = None
    UpcomingOpponent: Optional[str] = None
    UpcomingOpponentPositionRank: Optional[int] = None
    UpcomingOpponentRank: Optional[int] = None
    UpcomingSalary: Optional[int] = None
    UpcomingYahooSalary: Optional[int] = None
    WikipediaLogoUrl: Optional[str] = None
    WikipediaWordMarkUrl: Optional[str] = None
    YahooName: Optional[str] = None
    YahooPlayerID: Optional[int] = None


class TeamDepthChart(BaseModel):
    Defense: Optional[List[DepthChart]] = None
    Offense: Optional[List[DepthChart]] = None
    SpecialTeams: Optional[List[DepthChart]] = None
    TeamID: Optional[int] = None


class TeamGame(BaseModel):
    AssistedTackles: Optional[int] = None
    BlockedKickReturnTouchdowns: Optional[int] = None
    BlockedKickReturnYards: Optional[int] = None
    BlockedKicks: Optional[int] = None
    CompletionPercentage: Optional[float] = None
    Date: Optional[str] = None
    DateTime: Optional[str] = None
    Day: Optional[str] = None
    DayOfWeek: Optional[str] = None
    ExtraPointKickingAttempts: Optional[int] = None
    ExtraPointKickingConversions: Optional[int] = None
    ExtraPointPassingAttempts: Optional[int] = None
    ExtraPointPassingConversions: Optional[int] = None
    ExtraPointPercentage: Optional[float] = None
    ExtraPointRushingAttempts: Optional[int] = None
    ExtraPointRushingConversions: Optional[int] = None
    ExtraPointsHadBlocked: Optional[int] = None
    FieldGoalAttempts: Optional[int] = None
    FieldGoalPercentage: Optional[float] = None
    FieldGoalReturnTouchdowns: Optional[int] = None
    FieldGoalReturnYards: Optional[int] = None
    FieldGoalsHadBlocked: Optional[int] = None
    FieldGoalsMade: Optional[int] = None
    FirstDowns: Optional[int] = None
    FirstDownsByPassing: Optional[int] = None
    FirstDownsByPenalty: Optional[int] = None
    FirstDownsByRushing: Optional[int] = None
    FourthDownAttempts: Optional[int] = None
    FourthDownConversions: Optional[int] = None
    FourthDownPercentage: Optional[float] = None
    FumbleReturnTouchdowns: Optional[int] = None
    FumbleReturnYards: Optional[int] = None
    Fumbles: Optional[int] = None
    FumblesForced: Optional[int] = None
    FumblesLost: Optional[int] = None
    FumblesRecovered: Optional[int] = None
    GameKey: Optional[str] = None
    Giveaways: Optional[int] = None
    GlobalGameID: Optional[int] = None
    GlobalOpponentID: Optional[int] = None
    GlobalTeamID: Optional[int] = None
    GoalToGoAttempts: Optional[int] = None
    GoalToGoConversions: Optional[int] = None
    GoalToGoPercentage: Optional[float] = None
    HomeOrAway: Optional[str] = None
    Humidity: Optional[int] = None
    InterceptionReturnTouchdowns: Optional[int] = None
    InterceptionReturnYards: Optional[int] = None
    InterceptionReturns: Optional[int] = None
    IsGameOver: Optional[bool] = None
    KickReturnAverage: Optional[float] = None
    KickReturnLong: Optional[int] = None
    KickReturnTouchdowns: Optional[int] = None
    KickReturnYardDifferential: Optional[int] = None
    KickReturnYards: Optional[int] = None
    KickReturns: Optional[int] = None
    KickoffTouchbacks: Optional[int] = None
    Kickoffs: Optional[int] = None
    KickoffsInEndZone: Optional[int] = None
    OffensivePlays: Optional[int] = None
    OffensiveYards: Optional[int] = None
    OffensiveYardsPerPlay: Optional[float] = None
    Opponent: Optional[str] = None
    OpponentAssistedTackles: Optional[int] = None
    OpponentBlockedKickReturnTouchdowns: Optional[int] = None
    OpponentBlockedKickReturnYards: Optional[int] = None
    OpponentBlockedKicks: Optional[int] = None
    OpponentCompletionPercentage: Optional[float] = None
    OpponentExtraPointKickingAttempts: Optional[int] = None
    OpponentExtraPointKickingConversions: Optional[int] = None
    OpponentExtraPointPassingAttempts: Optional[int] = None
    OpponentExtraPointPassingConversions: Optional[int] = None
    OpponentExtraPointPercentage: Optional[float] = None
    OpponentExtraPointRushingAttempts: Optional[int] = None
    OpponentExtraPointRushingConversions: Optional[int] = None
    OpponentExtraPointsHadBlocked: Optional[int] = None
    OpponentFieldGoalAttempts: Optional[int] = None
    OpponentFieldGoalPercentage: Optional[float] = None
    OpponentFieldGoalReturnTouchdowns: Optional[int] = None
    OpponentFieldGoalReturnYards: Optional[int] = None
    OpponentFieldGoalsHadBlocked: Optional[int] = None
    OpponentFieldGoalsMade: Optional[int] = None
    OpponentFirstDowns: Optional[int] = None
    OpponentFirstDownsByPassing: Optional[int] = None
    OpponentFirstDownsByPenalty: Optional[int] = None
    OpponentFirstDownsByRushing: Optional[int] = None
    OpponentFourthDownAttempts: Optional[int] = None
    OpponentFourthDownConversions: Optional[int] = None
    OpponentFourthDownPercentage: Optional[float] = None
    OpponentFumbleReturnTouchdowns: Optional[int] = None
    OpponentFumbleReturnYards: Optional[int] = None
    OpponentFumbles: Optional[int] = None
    OpponentFumblesForced: Optional[int] = None
    OpponentFumblesLost: Optional[int] = None
    OpponentFumblesRecovered: Optional[int] = None
    OpponentGiveaways: Optional[int] = None
    OpponentGoalToGoAttempts: Optional[int] = None
    OpponentGoalToGoConversions: Optional[int] = None
    OpponentGoalToGoPercentage: Optional[float] = None
    OpponentID: Optional[int] = None
    OpponentInterceptionReturnTouchdowns: Optional[int] = None
    OpponentInterceptionReturnYards: Optional[int] = None
    OpponentInterceptionReturns: Optional[int] = None
    OpponentKickReturnAverage: Optional[float] = None
    OpponentKickReturnLong: Optional[int] = None
    OpponentKickReturnTouchdowns: Optional[int] = None
    OpponentKickReturnYards: Optional[int] = None
    OpponentKickReturns: Optional[int] = None
    OpponentKickoffTouchbacks: Optional[int] = None
    OpponentKickoffs: Optional[int] = None
    OpponentKickoffsInEndZone: Optional[int] = None
    OpponentOffensivePlays: Optional[int] = None
    OpponentOffensiveYards: Optional[int] = None
    OpponentOffensiveYardsPerPlay: Optional[float] = None
    OpponentPasserRating: Optional[float] = None
    OpponentPassesDefended: Optional[int] = None
    OpponentPassingAttempts: Optional[int] = None
    OpponentPassingCompletions: Optional[int] = None
    OpponentPassingDropbacks: Optional[int] = None
    OpponentPassingInterceptionPercentage: Optional[float] = None
    OpponentPassingInterceptions: Optional[int] = None
    OpponentPassingTouchdowns: Optional[int] = None
    OpponentPassingYards: Optional[int] = None
    OpponentPassingYardsPerAttempt: Optional[float] = None
    OpponentPassingYardsPerCompletion: Optional[float] = None
    OpponentPenalties: Optional[int] = None
    OpponentPenaltyYards: Optional[int] = None
    OpponentPuntAverage: Optional[float] = None
    OpponentPuntNetAverage: Optional[float] = None
    OpponentPuntNetYards: Optional[int] = None
    OpponentPuntReturnAverage: Optional[float] = None
    OpponentPuntReturnLong: Optional[int] = None
    OpponentPuntReturnTouchdowns: Optional[int] = None
    OpponentPuntReturnYards: Optional[int] = None
    OpponentPuntReturns: Optional[int] = None
    OpponentPuntYards: Optional[int] = None
    OpponentPunts: Optional[int] = None
    OpponentPuntsHadBlocked: Optional[int] = None
    OpponentQuarterbackHits: Optional[int] = None
    OpponentQuarterbackHitsDifferential: Optional[int] = None
    OpponentQuarterbackHitsPercentage: Optional[float] = None
    OpponentQuarterbackSacksDifferential: Optional[int] = None
    OpponentRedZoneAttempts: Optional[int] = None
    OpponentRedZoneConversions: Optional[int] = None
    OpponentRedZonePercentage: Optional[float] = None
    OpponentReturnYards: Optional[int] = None
    OpponentRushingAttempts: Optional[int] = None
    OpponentRushingTouchdowns: Optional[int] = None
    OpponentRushingYards: Optional[int] = None
    OpponentRushingYardsPerAttempt: Optional[float] = None
    OpponentSackYards: Optional[int] = None
    OpponentSacks: Optional[int] = None
    OpponentSafeties: Optional[int] = None
    OpponentScore: Optional[int] = None
    OpponentScoreOvertime: Optional[int] = None
    OpponentScoreQuarter1: Optional[int] = None
    OpponentScoreQuarter2: Optional[int] = None
    OpponentScoreQuarter3: Optional[int] = None
    OpponentScoreQuarter4: Optional[int] = None
    OpponentSoloTackles: Optional[int] = None
    OpponentTacklesForLoss: Optional[int] = None
    OpponentTacklesForLossDifferential: Optional[int] = None
    OpponentTacklesForLossPercentage: Optional[float] = None
    OpponentTakeaways: Optional[int] = None
    OpponentThirdDownAttempts: Optional[int] = None
    OpponentThirdDownConversions: Optional[int] = None
    OpponentThirdDownPercentage: Optional[float] = None
    OpponentTimeOfPossession: Optional[str] = None
    OpponentTimeOfPossessionMinutes: Optional[int] = None
    OpponentTimeOfPossessionSeconds: Optional[int] = None
    OpponentTimesSacked: Optional[int] = None
    OpponentTimesSackedPercentage: Optional[float] = None
    OpponentTimesSackedYards: Optional[int] = None
    OpponentTouchdowns: Optional[int] = None
    OpponentTurnoverDifferential: Optional[int] = None
    OpponentTwoPointConversionReturns: Optional[int] = None
    OverUnder: Optional[float] = None
    PasserRating: Optional[float] = None
    PassesDefended: Optional[int] = None
    PassingAttempts: Optional[int] = None
    PassingCompletions: Optional[int] = None
    PassingDropbacks: Optional[int] = None
    PassingInterceptionPercentage: Optional[float] = None
    PassingInterceptions: Optional[int] = None
    PassingTouchdowns: Optional[int] = None
    PassingYards: Optional[int] = None
    PassingYardsPerAttempt: Optional[float] = None
    PassingYardsPerCompletion: Optional[float] = None
    Penalties: Optional[int] = None
    PenaltyYardDifferential: Optional[int] = None
    PenaltyYards: Optional[int] = None
    PlayingSurface: Optional[str] = None
    PointDifferential: Optional[int] = None
    PointSpread: Optional[float] = None
    PuntAverage: Optional[float] = None
    PuntNetAverage: Optional[float] = None
    PuntNetYards: Optional[int] = None
    PuntReturnAverage: Optional[float] = None
    PuntReturnLong: Optional[int] = None
    PuntReturnTouchdowns: Optional[int] = None
    PuntReturnYardDifferential: Optional[int] = None
    PuntReturnYards: Optional[int] = None
    PuntReturns: Optional[int] = None
    PuntYards: Optional[int] = None
    Punts: Optional[int] = None
    PuntsHadBlocked: Optional[int] = None
    QuarterbackHits: Optional[int] = None
    QuarterbackHitsDifferential: Optional[int] = None
    QuarterbackHitsPercentage: Optional[float] = None
    QuarterbackSacksDifferential: Optional[int] = None
    RedZoneAttempts: Optional[int] = None
    RedZoneConversions: Optional[int] = None
    RedZonePercentage: Optional[float] = None
    ReturnYards: Optional[int] = None
    RushingAttempts: Optional[int] = None
    RushingTouchdowns: Optional[int] = None
    RushingYards: Optional[int] = None
    RushingYardsPerAttempt: Optional[float] = None
    SackYards: Optional[int] = None
    Sacks: Optional[int] = None
    Safeties: Optional[int] = None
    Score: Optional[int] = None
    ScoreID: Optional[int] = None
    ScoreOvertime: Optional[int] = None
    ScoreQuarter1: Optional[int] = None
    ScoreQuarter2: Optional[int] = None
    ScoreQuarter3: Optional[int] = None
    ScoreQuarter4: Optional[int] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    SoloTackles: Optional[int] = None
    Stadium: Optional[str] = None
    TacklesForLoss: Optional[int] = None
    TacklesForLossDifferential: Optional[int] = None
    TacklesForLossPercentage: Optional[float] = None
    Takeaways: Optional[int] = None
    Team: Optional[str] = None
    TeamGameID: Optional[int] = None
    TeamID: Optional[int] = None
    TeamName: Optional[str] = None
    Temperature: Optional[int] = None
    ThirdDownAttempts: Optional[int] = None
    ThirdDownConversions: Optional[int] = None
    ThirdDownPercentage: Optional[float] = None
    TimeOfPossession: Optional[str] = None
    TimeOfPossessionMinutes: Optional[int] = None
    TimeOfPossessionSeconds: Optional[int] = None
    TimesSacked: Optional[int] = None
    TimesSackedPercentage: Optional[float] = None
    TimesSackedYards: Optional[int] = None
    TotalScore: Optional[int] = None
    Touchdowns: Optional[int] = None
    TurnoverDifferential: Optional[int] = None
    TwoPointConversionReturns: Optional[int] = None
    Week: Optional[int] = None
    WindSpeed: Optional[int] = None


class TeamSeason(BaseModel):
    AssistedTackles: Optional[int] = None
    BlockedKickReturnTouchdowns: Optional[int] = None
    BlockedKickReturnYards: Optional[int] = None
    BlockedKicks: Optional[int] = None
    CompletionPercentage: Optional[float] = None
    ExtraPointKickingAttempts: Optional[int] = None
    ExtraPointKickingConversions: Optional[int] = None
    ExtraPointPassingAttempts: Optional[int] = None
    ExtraPointPassingConversions: Optional[int] = None
    ExtraPointPercentage: Optional[float] = None
    ExtraPointRushingAttempts: Optional[int] = None
    ExtraPointRushingConversions: Optional[int] = None
    ExtraPointsHadBlocked: Optional[int] = None
    FieldGoalAttempts: Optional[int] = None
    FieldGoalPercentage: Optional[float] = None
    FieldGoalReturnTouchdowns: Optional[int] = None
    FieldGoalReturnYards: Optional[int] = None
    FieldGoalsHadBlocked: Optional[int] = None
    FieldGoalsMade: Optional[int] = None
    FirstDowns: Optional[int] = None
    FirstDownsByPassing: Optional[int] = None
    FirstDownsByPenalty: Optional[int] = None
    FirstDownsByRushing: Optional[int] = None
    FourthDownAttempts: Optional[int] = None
    FourthDownConversions: Optional[int] = None
    FourthDownPercentage: Optional[float] = None
    FumbleReturnTouchdowns: Optional[int] = None
    FumbleReturnYards: Optional[int] = None
    Fumbles: Optional[int] = None
    FumblesForced: Optional[int] = None
    FumblesLost: Optional[int] = None
    FumblesRecovered: Optional[int] = None
    Games: Optional[int] = None
    Giveaways: Optional[int] = None
    GlobalTeamID: Optional[int] = None
    GoalToGoAttempts: Optional[int] = None
    GoalToGoConversions: Optional[int] = None
    GoalToGoPercentage: Optional[float] = None
    Humidity: Optional[int] = None
    InterceptionReturnTouchdowns: Optional[int] = None
    InterceptionReturnYards: Optional[int] = None
    InterceptionReturns: Optional[int] = None
    KickReturnAverage: Optional[float] = None
    KickReturnLong: Optional[int] = None
    KickReturnTouchdowns: Optional[int] = None
    KickReturnYardDifferential: Optional[int] = None
    KickReturnYards: Optional[int] = None
    KickReturns: Optional[int] = None
    KickoffTouchbacks: Optional[int] = None
    Kickoffs: Optional[int] = None
    KickoffsInEndZone: Optional[int] = None
    OffensivePlays: Optional[int] = None
    OffensiveYards: Optional[int] = None
    OffensiveYardsPerPlay: Optional[float] = None
    OpponentAssistedTackles: Optional[int] = None
    OpponentBlockedKickReturnTouchdowns: Optional[int] = None
    OpponentBlockedKickReturnYards: Optional[int] = None
    OpponentBlockedKicks: Optional[int] = None
    OpponentCompletionPercentage: Optional[float] = None
    OpponentExtraPointKickingAttempts: Optional[int] = None
    OpponentExtraPointKickingConversions: Optional[int] = None
    OpponentExtraPointPassingAttempts: Optional[int] = None
    OpponentExtraPointPassingConversions: Optional[int] = None
    OpponentExtraPointPercentage: Optional[float] = None
    OpponentExtraPointRushingAttempts: Optional[int] = None
    OpponentExtraPointRushingConversions: Optional[int] = None
    OpponentExtraPointsHadBlocked: Optional[int] = None
    OpponentFieldGoalAttempts: Optional[int] = None
    OpponentFieldGoalPercentage: Optional[float] = None
    OpponentFieldGoalReturnTouchdowns: Optional[int] = None
    OpponentFieldGoalReturnYards: Optional[int] = None
    OpponentFieldGoalsHadBlocked: Optional[int] = None
    OpponentFieldGoalsMade: Optional[int] = None
    OpponentFirstDowns: Optional[int] = None
    OpponentFirstDownsByPassing: Optional[int] = None
    OpponentFirstDownsByPenalty: Optional[int] = None
    OpponentFirstDownsByRushing: Optional[int] = None
    OpponentFourthDownAttempts: Optional[int] = None
    OpponentFourthDownConversions: Optional[int] = None
    OpponentFourthDownPercentage: Optional[float] = None
    OpponentFumbleReturnTouchdowns: Optional[int] = None
    OpponentFumbleReturnYards: Optional[int] = None
    OpponentFumbles: Optional[int] = None
    OpponentFumblesForced: Optional[int] = None
    OpponentFumblesLost: Optional[int] = None
    OpponentFumblesRecovered: Optional[int] = None
    OpponentGiveaways: Optional[int] = None
    OpponentGoalToGoAttempts: Optional[int] = None
    OpponentGoalToGoConversions: Optional[int] = None
    OpponentGoalToGoPercentage: Optional[float] = None
    OpponentInterceptionReturnTouchdowns: Optional[int] = None
    OpponentInterceptionReturnYards: Optional[int] = None
    OpponentInterceptionReturns: Optional[int] = None
    OpponentKickReturnAverage: Optional[float] = None
    OpponentKickReturnLong: Optional[int] = None
    OpponentKickReturnTouchdowns: Optional[int] = None
    OpponentKickReturnYards: Optional[int] = None
    OpponentKickReturns: Optional[int] = None
    OpponentKickoffTouchbacks: Optional[int] = None
    OpponentKickoffs: Optional[int] = None
    OpponentKickoffsInEndZone: Optional[int] = None
    OpponentOffensivePlays: Optional[int] = None
    OpponentOffensiveYards: Optional[int] = None
    OpponentOffensiveYardsPerPlay: Optional[float] = None
    OpponentPasserRating: Optional[float] = None
    OpponentPassesDefended: Optional[int] = None
    OpponentPassingAttempts: Optional[int] = None
    OpponentPassingCompletions: Optional[int] = None
    OpponentPassingDropbacks: Optional[int] = None
    OpponentPassingInterceptionPercentage: Optional[float] = None
    OpponentPassingInterceptions: Optional[int] = None
    OpponentPassingTouchdowns: Optional[int] = None
    OpponentPassingYards: Optional[int] = None
    OpponentPassingYardsPerAttempt: Optional[float] = None
    OpponentPassingYardsPerCompletion: Optional[float] = None
    OpponentPenalties: Optional[int] = None
    OpponentPenaltyYards: Optional[int] = None
    OpponentPuntAverage: Optional[float] = None
    OpponentPuntNetAverage: Optional[float] = None
    OpponentPuntNetYards: Optional[int] = None
    OpponentPuntReturnAverage: Optional[float] = None
    OpponentPuntReturnLong: Optional[int] = None
    OpponentPuntReturnTouchdowns: Optional[int] = None
    OpponentPuntReturnYards: Optional[int] = None
    OpponentPuntReturns: Optional[int] = None
    OpponentPuntYards: Optional[int] = None
    OpponentPunts: Optional[int] = None
    OpponentPuntsHadBlocked: Optional[int] = None
    OpponentQuarterbackHits: Optional[int] = None
    OpponentQuarterbackHitsDifferential: Optional[int] = None
    OpponentQuarterbackHitsPercentage: Optional[float] = None
    OpponentQuarterbackSacksDifferential: Optional[int] = None
    OpponentRedZoneAttempts: Optional[int] = None
    OpponentRedZoneConversions: Optional[int] = None
    OpponentRedZonePercentage: Optional[float] = None
    OpponentReturnYards: Optional[int] = None
    OpponentRushingAttempts: Optional[int] = None
    OpponentRushingTouchdowns: Optional[int] = None
    OpponentRushingYards: Optional[int] = None
    OpponentRushingYardsPerAttempt: Optional[float] = None
    OpponentSackYards: Optional[int] = None
    OpponentSacks: Optional[int] = None
    OpponentSafeties: Optional[int] = None
    OpponentScore: Optional[int] = None
    OpponentScoreOvertime: Optional[int] = None
    OpponentScoreQuarter1: Optional[int] = None
    OpponentScoreQuarter2: Optional[int] = None
    OpponentScoreQuarter3: Optional[int] = None
    OpponentScoreQuarter4: Optional[int] = None
    OpponentSoloTackles: Optional[int] = None
    OpponentTacklesForLoss: Optional[int] = None
    OpponentTacklesForLossDifferential: Optional[int] = None
    OpponentTacklesForLossPercentage: Optional[float] = None
    OpponentTakeaways: Optional[int] = None
    OpponentThirdDownAttempts: Optional[int] = None
    OpponentThirdDownConversions: Optional[int] = None
    OpponentThirdDownPercentage: Optional[float] = None
    OpponentTimeOfPossession: Optional[str] = None
    OpponentTimesSacked: Optional[int] = None
    OpponentTimesSackedPercentage: Optional[float] = None
    OpponentTimesSackedYards: Optional[int] = None
    OpponentTouchdowns: Optional[int] = None
    OpponentTurnoverDifferential: Optional[int] = None
    OpponentTwoPointConversionReturns: Optional[int] = None
    OverUnder: Optional[float] = None
    PasserRating: Optional[float] = None
    PassesDefended: Optional[int] = None
    PassingAttempts: Optional[int] = None
    PassingCompletions: Optional[int] = None
    PassingDropbacks: Optional[int] = None
    PassingInterceptionPercentage: Optional[float] = None
    PassingInterceptions: Optional[int] = None
    PassingTouchdowns: Optional[int] = None
    PassingYards: Optional[int] = None
    PassingYardsPerAttempt: Optional[float] = None
    PassingYardsPerCompletion: Optional[float] = None
    Penalties: Optional[int] = None
    PenaltyYardDifferential: Optional[int] = None
    PenaltyYards: Optional[int] = None
    PointDifferential: Optional[int] = None
    PointSpread: Optional[float] = None
    PuntAverage: Optional[float] = None
    PuntNetAverage: Optional[float] = None
    PuntNetYards: Optional[int] = None
    PuntReturnAverage: Optional[float] = None
    PuntReturnLong: Optional[int] = None
    PuntReturnTouchdowns: Optional[int] = None
    PuntReturnYardDifferential: Optional[int] = None
    PuntReturnYards: Optional[int] = None
    PuntReturns: Optional[int] = None
    PuntYards: Optional[int] = None
    Punts: Optional[int] = None
    PuntsHadBlocked: Optional[int] = None
    QuarterbackHits: Optional[int] = None
    QuarterbackHitsDifferential: Optional[int] = None
    QuarterbackHitsPercentage: Optional[float] = None
    QuarterbackSacksDifferential: Optional[int] = None
    RedZoneAttempts: Optional[int] = None
    RedZoneConversions: Optional[int] = None
    RedZonePercentage: Optional[float] = None
    ReturnYards: Optional[int] = None
    RushingAttempts: Optional[int] = None
    RushingTouchdowns: Optional[int] = None
    RushingYards: Optional[int] = None
    RushingYardsPerAttempt: Optional[float] = None
    SackYards: Optional[int] = None
    Sacks: Optional[int] = None
    Safeties: Optional[int] = None
    Score: Optional[int] = None
    ScoreOvertime: Optional[int] = None
    ScoreQuarter1: Optional[int] = None
    ScoreQuarter2: Optional[int] = None
    ScoreQuarter3: Optional[int] = None
    ScoreQuarter4: Optional[int] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    SoloTackles: Optional[int] = None
    TacklesForLoss: Optional[int] = None
    TacklesForLossDifferential: Optional[int] = None
    TacklesForLossPercentage: Optional[float] = None
    Takeaways: Optional[int] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    TeamName: Optional[str] = None
    TeamSeasonID: Optional[int] = None
    TeamStatID: Optional[int] = None
    Temperature: Optional[int] = None
    ThirdDownAttempts: Optional[int] = None
    ThirdDownConversions: Optional[int] = None
    ThirdDownPercentage: Optional[float] = None
    TimeOfPossession: Optional[str] = None
    TimesSacked: Optional[int] = None
    TimesSackedPercentage: Optional[float] = None
    TimesSackedYards: Optional[int] = None
    TotalScore: Optional[int] = None
    Touchdowns: Optional[int] = None
    TurnoverDifferential: Optional[int] = None
    TwoPointConversionReturns: Optional[int] = None
    WindSpeed: Optional[int] = None


class Timeframe(BaseModel):
    ApiSeason: Optional[str] = None
    ApiWeek: Optional[str] = None
    EndDate: Optional[str] = None
    FirstGameEnd: Optional[str] = None
    FirstGameStart: Optional[str] = None
    HasEnded: Optional[bool] = None
    HasFirstGameEnded: Optional[bool] = None
    HasFirstGameStarted: Optional[bool] = None
    HasGames: Optional[bool] = None
    HasLastGameEnded: Optional[bool] = None
    HasStarted: Optional[bool] = None
    LastGameEnd: Optional[str] = None
    Name: Optional[str] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    ShortName: Optional[str] = None
    StartDate: Optional[str] = None
    Week: Optional[int] = None


class FieldFormatAllTeamsGetResponse(RootModel[List[Team]]):
    root: List[Team]


class Format(Enum):
    XML = 'XML'
    JSON = 'JSON'


class FieldFormatByesSeasonGetResponse(RootModel[List[Bye]]):
    root: List[Bye]


class FieldFormatDepthChartsGetResponse(RootModel[List[TeamDepthChart]]):
    root: List[TeamDepthChart]


class FieldFormatFreeAgentsGetResponse(RootModel[List[Player]]):
    root: List[Player]


class FieldFormatNewsGetResponse(RootModel[List[News]]):
    root: List[News]


class FieldFormatNewsByDateDateGetResponse(RootModel[List[News]]):
    root: List[News]


class FieldFormatNewsByPlayerIDPlayeridGetResponse(RootModel[List[News]]):
    root: List[News]


class FieldFormatNewsByTeamTeamGetResponse(RootModel[List[News]]):
    root: List[News]


class FieldFormatPlayersGetResponse(RootModel[List[Player]]):
    root: List[Player]


class FieldFormatRefereesGetResponse(RootModel[List[Referee]]):
    root: List[Referee]


class FieldFormatRookiesSeasonGetResponse(RootModel[List[Player]]):
    root: List[Player]


class FieldFormatStadiumsGetResponse(RootModel[List[Stadium]]):
    root: List[Stadium]


class FieldFormatStandingsSeasonGetResponse(RootModel[List[Standing]]):
    root: List[Standing]


class FieldFormatTeamGameStatsSeasonWeekGetResponse(RootModel[List[TeamGame]]):
    root: List[TeamGame]


class FieldFormatTeamGameStatsBySeasonSeasonTeamidNumberofgamesGetResponse(
    RootModel[List[TeamGame]]
):
    root: List[TeamGame]


class FieldFormatTeamSeasonStatsSeasonGetResponse(RootModel[List[TeamSeason]]):
    root: List[TeamSeason]


class FieldFormatTeamsGetResponse(RootModel[List[Team]]):
    root: List[Team]


class FieldFormatTeamsSeasonGetResponse(RootModel[List[Team]]):
    root: List[Team]


class FieldFormatTimeframesTypeGetResponse(RootModel[List[Timeframe]]):
    root: List[Timeframe]


class Type(Enum):
    current = 'current'
    upcoming = 'upcoming'
    completed = 'completed'
    recent = 'recent'
    all = 'all'


class Game(BaseModel):
    AwayAssistedTackles: Optional[int] = None
    AwayBlockedKickReturnTouchdowns: Optional[int] = None
    AwayBlockedKickReturnYards: Optional[int] = None
    AwayBlockedKicks: Optional[int] = None
    AwayCompletionPercentage: Optional[float] = None
    AwayExtraPointKickingAttempts: Optional[int] = None
    AwayExtraPointKickingConversions: Optional[int] = None
    AwayExtraPointPassingAttempts: Optional[int] = None
    AwayExtraPointPassingConversions: Optional[int] = None
    AwayExtraPointRushingAttempts: Optional[int] = None
    AwayExtraPointRushingConversions: Optional[int] = None
    AwayExtraPointsHadBlocked: Optional[int] = None
    AwayFieldGoalAttempts: Optional[int] = None
    AwayFieldGoalReturnTouchdowns: Optional[int] = None
    AwayFieldGoalReturnYards: Optional[int] = None
    AwayFieldGoalsHadBlocked: Optional[int] = None
    AwayFieldGoalsMade: Optional[int] = None
    AwayFirstDowns: Optional[int] = None
    AwayFirstDownsByPassing: Optional[int] = None
    AwayFirstDownsByPenalty: Optional[int] = None
    AwayFirstDownsByRushing: Optional[int] = None
    AwayFourthDownAttempts: Optional[int] = None
    AwayFourthDownConversions: Optional[int] = None
    AwayFourthDownPercentage: Optional[float] = None
    AwayFumbleReturnTouchdowns: Optional[int] = None
    AwayFumbleReturnYards: Optional[int] = None
    AwayFumbles: Optional[int] = None
    AwayFumblesForced: Optional[int] = None
    AwayFumblesLost: Optional[int] = None
    AwayFumblesRecovered: Optional[int] = None
    AwayGiveaways: Optional[int] = None
    AwayGoalToGoAttempts: Optional[int] = None
    AwayGoalToGoConversions: Optional[int] = None
    AwayInterceptionReturnTouchdowns: Optional[int] = None
    AwayInterceptionReturnYards: Optional[int] = None
    AwayInterceptionReturns: Optional[int] = None
    AwayKickReturnLong: Optional[int] = None
    AwayKickReturnTouchdowns: Optional[int] = None
    AwayKickReturnYards: Optional[int] = None
    AwayKickReturns: Optional[int] = None
    AwayKickoffTouchbacks: Optional[int] = None
    AwayKickoffs: Optional[int] = None
    AwayKickoffsInEndZone: Optional[int] = None
    AwayOffensivePlays: Optional[int] = None
    AwayOffensiveYards: Optional[int] = None
    AwayOffensiveYardsPerPlay: Optional[float] = None
    AwayPasserRating: Optional[float] = None
    AwayPassesDefended: Optional[int] = None
    AwayPassingAttempts: Optional[int] = None
    AwayPassingCompletions: Optional[int] = None
    AwayPassingInterceptions: Optional[int] = None
    AwayPassingTouchdowns: Optional[int] = None
    AwayPassingYards: Optional[int] = None
    AwayPassingYardsPerAttempt: Optional[float] = None
    AwayPassingYardsPerCompletion: Optional[float] = None
    AwayPenalties: Optional[int] = None
    AwayPenaltyYards: Optional[int] = None
    AwayPuntAverage: Optional[float] = None
    AwayPuntNetAverage: Optional[float] = None
    AwayPuntNetYards: Optional[int] = None
    AwayPuntReturnLong: Optional[int] = None
    AwayPuntReturnTouchdowns: Optional[int] = None
    AwayPuntReturnYards: Optional[int] = None
    AwayPuntReturns: Optional[int] = None
    AwayPuntYards: Optional[int] = None
    AwayPunts: Optional[int] = None
    AwayPuntsHadBlocked: Optional[int] = None
    AwayQuarterbackHits: Optional[int] = None
    AwayRedZoneAttempts: Optional[int] = None
    AwayRedZoneConversions: Optional[int] = None
    AwayReturnYards: Optional[int] = None
    AwayRushingAttempts: Optional[int] = None
    AwayRushingTouchdowns: Optional[int] = None
    AwayRushingYards: Optional[int] = None
    AwayRushingYardsPerAttempt: Optional[float] = None
    AwaySackYards: Optional[int] = None
    AwaySacks: Optional[int] = None
    AwaySafeties: Optional[int] = None
    AwayScore: Optional[int] = None
    AwayScoreOvertime: Optional[int] = None
    AwayScoreQuarter1: Optional[int] = None
    AwayScoreQuarter2: Optional[int] = None
    AwayScoreQuarter3: Optional[int] = None
    AwayScoreQuarter4: Optional[int] = None
    AwaySoloTackles: Optional[int] = None
    AwayTacklesForLoss: Optional[int] = None
    AwayTakeaways: Optional[int] = None
    AwayTeam: Optional[str] = None
    AwayThirdDownAttempts: Optional[int] = None
    AwayThirdDownConversions: Optional[int] = None
    AwayThirdDownPercentage: Optional[float] = None
    AwayTimeOfPossession: Optional[str] = None
    AwayTimesSacked: Optional[int] = None
    AwayTimesSackedYards: Optional[int] = None
    AwayTouchdowns: Optional[int] = None
    AwayTurnoverDifferential: Optional[int] = None
    AwayTwoPointConversionReturns: Optional[int] = None
    Date: Optional[str] = None
    GameID: Optional[int] = None
    GameKey: Optional[str] = None
    HomeAssistedTackles: Optional[int] = None
    HomeBlockedKickReturnTouchdowns: Optional[int] = None
    HomeBlockedKickReturnYards: Optional[int] = None
    HomeBlockedKicks: Optional[int] = None
    HomeCompletionPercentage: Optional[float] = None
    HomeExtraPointKickingAttempts: Optional[int] = None
    HomeExtraPointKickingConversions: Optional[int] = None
    HomeExtraPointPassingAttempts: Optional[int] = None
    HomeExtraPointPassingConversions: Optional[int] = None
    HomeExtraPointRushingAttempts: Optional[int] = None
    HomeExtraPointRushingConversions: Optional[int] = None
    HomeExtraPointsHadBlocked: Optional[int] = None
    HomeFieldGoalAttempts: Optional[int] = None
    HomeFieldGoalReturnTouchdowns: Optional[int] = None
    HomeFieldGoalReturnYards: Optional[int] = None
    HomeFieldGoalsHadBlocked: Optional[int] = None
    HomeFieldGoalsMade: Optional[int] = None
    HomeFirstDowns: Optional[int] = None
    HomeFirstDownsByPassing: Optional[int] = None
    HomeFirstDownsByPenalty: Optional[int] = None
    HomeFirstDownsByRushing: Optional[int] = None
    HomeFourthDownAttempts: Optional[int] = None
    HomeFourthDownConversions: Optional[int] = None
    HomeFourthDownPercentage: Optional[float] = None
    HomeFumbleReturnTouchdowns: Optional[int] = None
    HomeFumbleReturnYards: Optional[int] = None
    HomeFumbles: Optional[int] = None
    HomeFumblesForced: Optional[int] = None
    HomeFumblesLost: Optional[int] = None
    HomeFumblesRecovered: Optional[int] = None
    HomeGiveaways: Optional[int] = None
    HomeGoalToGoAttempts: Optional[int] = None
    HomeGoalToGoConversions: Optional[int] = None
    HomeInterceptionReturnTouchdowns: Optional[int] = None
    HomeInterceptionReturnYards: Optional[int] = None
    HomeInterceptionReturns: Optional[int] = None
    HomeKickReturnLong: Optional[int] = None
    HomeKickReturnTouchdowns: Optional[int] = None
    HomeKickReturnYards: Optional[int] = None
    HomeKickReturns: Optional[int] = None
    HomeKickoffTouchbacks: Optional[int] = None
    HomeKickoffs: Optional[int] = None
    HomeKickoffsInEndZone: Optional[int] = None
    HomeOffensivePlays: Optional[int] = None
    HomeOffensiveYards: Optional[int] = None
    HomeOffensiveYardsPerPlay: Optional[float] = None
    HomePasserRating: Optional[float] = None
    HomePassesDefended: Optional[int] = None
    HomePassingAttempts: Optional[int] = None
    HomePassingCompletions: Optional[int] = None
    HomePassingInterceptions: Optional[int] = None
    HomePassingTouchdowns: Optional[int] = None
    HomePassingYards: Optional[int] = None
    HomePassingYardsPerAttempt: Optional[float] = None
    HomePassingYardsPerCompletion: Optional[float] = None
    HomePenalties: Optional[int] = None
    HomePenaltyYards: Optional[int] = None
    HomePuntAverage: Optional[float] = None
    HomePuntNetAverage: Optional[float] = None
    HomePuntNetYards: Optional[int] = None
    HomePuntReturnLong: Optional[int] = None
    HomePuntReturnTouchdowns: Optional[int] = None
    HomePuntReturnYards: Optional[int] = None
    HomePuntReturns: Optional[int] = None
    HomePuntYards: Optional[int] = None
    HomePunts: Optional[int] = None
    HomePuntsHadBlocked: Optional[int] = None
    HomeQuarterbackHits: Optional[int] = None
    HomeRedZoneAttempts: Optional[int] = None
    HomeRedZoneConversions: Optional[int] = None
    HomeReturnYards: Optional[int] = None
    HomeRushingAttempts: Optional[int] = None
    HomeRushingTouchdowns: Optional[int] = None
    HomeRushingYards: Optional[int] = None
    HomeRushingYardsPerAttempt: Optional[float] = None
    HomeSackYards: Optional[int] = None
    HomeSacks: Optional[int] = None
    HomeSafeties: Optional[int] = None
    HomeScore: Optional[int] = None
    HomeScoreOvertime: Optional[int] = None
    HomeScoreQuarter1: Optional[int] = None
    HomeScoreQuarter2: Optional[int] = None
    HomeScoreQuarter3: Optional[int] = None
    HomeScoreQuarter4: Optional[int] = None
    HomeSoloTackles: Optional[int] = None
    HomeTacklesForLoss: Optional[int] = None
    HomeTakeaways: Optional[int] = None
    HomeTeam: Optional[str] = None
    HomeThirdDownAttempts: Optional[int] = None
    HomeThirdDownConversions: Optional[int] = None
    HomeThirdDownPercentage: Optional[float] = None
    HomeTimeOfPossession: Optional[str] = None
    HomeTimesSacked: Optional[int] = None
    HomeTimesSackedYards: Optional[int] = None
    HomeTouchdowns: Optional[int] = None
    HomeTurnoverDifferential: Optional[int] = None
    HomeTwoPointConversionReturns: Optional[int] = None
    Humidity: Optional[int] = None
    IsGameOver: Optional[bool] = None
    OverUnder: Optional[float] = None
    PlayingSurface: Optional[str] = None
    PointSpread: Optional[float] = None
    ScoreID: Optional[int] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    Stadium: Optional[str] = None
    StadiumDetails: Optional[Stadium] = None
    StadiumID: Optional[int] = None
    Temperature: Optional[int] = None
    TotalScore: Optional[int] = None
    Week: Optional[int] = None
    WindSpeed: Optional[int] = None


class PlayerSeason(BaseModel):
    Activated: Optional[int] = None
    AssistedTackles: Optional[float] = None
    AuctionValue: Optional[float] = None
    AuctionValuePPR: Optional[float] = None
    AverageDraftPosition: Optional[float] = None
    AverageDraftPosition2QB: Optional[float] = None
    AverageDraftPositionDynasty: Optional[float] = None
    AverageDraftPositionPPR: Optional[float] = None
    AverageDraftPositionRookie: Optional[float] = None
    BlockedKickReturnTouchdowns: Optional[float] = None
    BlockedKickReturnYards: Optional[float] = None
    BlockedKicks: Optional[float] = None
    DefensiveSnapsPlayed: Optional[int] = None
    DefensiveTeamSnaps: Optional[int] = None
    DefensiveTouchdowns: Optional[float] = None
    ExtraPointsAttempted: Optional[float] = None
    ExtraPointsHadBlocked: Optional[float] = None
    ExtraPointsMade: Optional[float] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsFantasyDraft: Optional[float] = None
    FantasyPointsPPR: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    FantasyPosition: Optional[str] = None
    FieldGoalPercentage: Optional[float] = None
    FieldGoalReturnTouchdowns: Optional[float] = None
    FieldGoalReturnYards: Optional[float] = None
    FieldGoalsAttempted: Optional[float] = None
    FieldGoalsHadBlocked: Optional[float] = None
    FieldGoalsLongestMade: Optional[float] = None
    FieldGoalsMade: Optional[float] = None
    FieldGoalsMade0to19: Optional[float] = None
    FieldGoalsMade20to29: Optional[float] = None
    FieldGoalsMade30to39: Optional[float] = None
    FieldGoalsMade40to49: Optional[float] = None
    FieldGoalsMade50Plus: Optional[float] = None
    FumbleReturnTouchdowns: Optional[float] = None
    FumbleReturnYards: Optional[float] = None
    Fumbles: Optional[float] = None
    FumblesForced: Optional[float] = None
    FumblesLost: Optional[float] = None
    FumblesOutOfBounds: Optional[float] = None
    FumblesOwnRecoveries: Optional[float] = None
    FumblesRecovered: Optional[float] = None
    GlobalTeamID: Optional[int] = None
    Humidity: Optional[int] = None
    InterceptionReturnTouchdowns: Optional[float] = None
    InterceptionReturnYards: Optional[float] = None
    Interceptions: Optional[float] = None
    KickReturnFairCatches: Optional[float] = None
    KickReturnLong: Optional[float] = None
    KickReturnTouchdowns: Optional[float] = None
    KickReturnYards: Optional[float] = None
    KickReturnYardsPerAttempt: Optional[float] = None
    KickReturns: Optional[float] = None
    MiscAssistedTackles: Optional[float] = None
    MiscFumblesForced: Optional[float] = None
    MiscFumblesRecovered: Optional[float] = None
    MiscSoloTackles: Optional[float] = None
    Name: Optional[str] = None
    Number: Optional[int] = None
    OffensiveFumbleRecoveryTouchdowns: Optional[int] = None
    OffensiveSnapsPlayed: Optional[int] = None
    OffensiveTeamSnaps: Optional[int] = None
    OffensiveTouchdowns: Optional[float] = None
    PassesDefended: Optional[float] = None
    PassingAttempts: Optional[float] = None
    PassingCompletionPercentage: Optional[float] = None
    PassingCompletions: Optional[float] = None
    PassingInterceptions: Optional[float] = None
    PassingLong: Optional[float] = None
    PassingRating: Optional[float] = None
    PassingSackYards: Optional[float] = None
    PassingSacks: Optional[float] = None
    PassingTouchdowns: Optional[float] = None
    PassingYards: Optional[float] = None
    PassingYardsPerAttempt: Optional[float] = None
    PassingYardsPerCompletion: Optional[float] = None
    Played: Optional[int] = None
    PlayerID: Optional[int] = None
    PlayerSeasonID: Optional[int] = None
    Position: Optional[str] = None
    PositionCategory: Optional[str] = None
    PuntAverage: Optional[float] = None
    PuntInside20: Optional[float] = None
    PuntLong: Optional[float] = None
    PuntNetAverage: Optional[float] = None
    PuntNetYards: Optional[float] = None
    PuntReturnFairCatches: Optional[float] = None
    PuntReturnLong: Optional[float] = None
    PuntReturnTouchdowns: Optional[float] = None
    PuntReturnYards: Optional[float] = None
    PuntReturnYardsPerAttempt: Optional[float] = None
    PuntReturns: Optional[float] = None
    PuntTouchbacks: Optional[float] = None
    PuntYards: Optional[float] = None
    Punts: Optional[float] = None
    PuntsHadBlocked: Optional[float] = None
    QuarterbackHits: Optional[float] = None
    ReceivingLong: Optional[float] = None
    ReceivingTargets: Optional[float] = None
    ReceivingTouchdowns: Optional[float] = None
    ReceivingYards: Optional[float] = None
    ReceivingYardsPerReception: Optional[float] = None
    ReceivingYardsPerTarget: Optional[float] = None
    ReceptionPercentage: Optional[float] = None
    Receptions: Optional[float] = None
    RushingAttempts: Optional[float] = None
    RushingLong: Optional[float] = None
    RushingTouchdowns: Optional[float] = None
    RushingYards: Optional[float] = None
    RushingYardsPerAttempt: Optional[float] = None
    SackYards: Optional[float] = None
    Sacks: Optional[float] = None
    Safeties: Optional[float] = None
    SafetiesAllowed: Optional[float] = None
    ScoringDetails: Optional[List[ScoringDetail]] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    ShortName: Optional[str] = None
    SoloTackles: Optional[float] = None
    SpecialTeamsAssistedTackles: Optional[float] = None
    SpecialTeamsFumblesForced: Optional[float] = None
    SpecialTeamsFumblesRecovered: Optional[float] = None
    SpecialTeamsSnapsPlayed: Optional[int] = None
    SpecialTeamsSoloTackles: Optional[float] = None
    SpecialTeamsTeamSnaps: Optional[int] = None
    SpecialTeamsTouchdowns: Optional[float] = None
    Started: Optional[int] = None
    Tackles: Optional[float] = None
    TacklesForLoss: Optional[float] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    Temperature: Optional[int] = None
    Touchdowns: Optional[float] = None
    TwoPointConversionPasses: Optional[float] = None
    TwoPointConversionReceptions: Optional[float] = None
    TwoPointConversionReturns: Optional[float] = None
    TwoPointConversionRuns: Optional[float] = None
    WindSpeed: Optional[int] = None


class Schedule(BaseModel):
    AwayTeam: Optional[str] = None
    AwayTeamMoneyLine: Optional[int] = None
    Canceled: Optional[bool] = None
    Channel: Optional[str] = None
    Date: Optional[str] = None
    DateTime: Optional[str] = None
    Day: Optional[str] = None
    ForecastDescription: Optional[str] = None
    ForecastTempHigh: Optional[int] = None
    ForecastTempLow: Optional[int] = None
    ForecastWindChill: Optional[int] = None
    ForecastWindSpeed: Optional[int] = None
    GameKey: Optional[str] = None
    GeoLat: Optional[float] = None
    GeoLong: Optional[float] = None
    GlobalAwayTeamID: Optional[int] = None
    GlobalGameID: Optional[int] = None
    GlobalHomeTeamID: Optional[int] = None
    HomeTeam: Optional[str] = None
    HomeTeamMoneyLine: Optional[int] = None
    OverUnder: Optional[float] = None
    PointSpread: Optional[float] = None
    ScoreID: Optional[int] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    StadiumDetails: Optional[Stadium] = None
    StadiumID: Optional[int] = None
    Status: Optional[str] = None
    Week: Optional[int] = None


class Score(BaseModel):
    Attendance: Optional[int] = None
    AwayRotationNumber: Optional[int] = None
    AwayScore: Optional[int] = None
    AwayScoreOvertime: Optional[int] = None
    AwayScoreQuarter1: Optional[int] = None
    AwayScoreQuarter2: Optional[int] = None
    AwayScoreQuarter3: Optional[int] = None
    AwayScoreQuarter4: Optional[int] = None
    AwayTeam: Optional[str] = None
    AwayTeamID: Optional[int] = None
    AwayTeamMoneyLine: Optional[int] = None
    AwayTimeouts: Optional[int] = None
    Canceled: Optional[bool] = None
    Channel: Optional[str] = None
    Closed: Optional[bool] = None
    Date: Optional[str] = None
    DateTime: Optional[str] = None
    DateTimeUTC: Optional[str] = None
    Day: Optional[str] = None
    Distance: Optional[str] = None
    Down: Optional[int] = None
    DownAndDistance: Optional[str] = None
    ForecastDescription: Optional[str] = None
    ForecastTempHigh: Optional[int] = None
    ForecastTempLow: Optional[int] = None
    ForecastWindChill: Optional[int] = None
    ForecastWindSpeed: Optional[int] = None
    GameEndDateTime: Optional[str] = None
    GameKey: Optional[str] = None
    GeoLat: Optional[float] = None
    GeoLong: Optional[float] = None
    GlobalAwayTeamID: Optional[int] = None
    GlobalGameID: Optional[int] = None
    GlobalHomeTeamID: Optional[int] = None
    Has1stQuarterStarted: Optional[bool] = None
    Has2ndQuarterStarted: Optional[bool] = None
    Has3rdQuarterStarted: Optional[bool] = None
    Has4thQuarterStarted: Optional[bool] = None
    HasStarted: Optional[bool] = None
    HomeRotationNumber: Optional[int] = None
    HomeScore: Optional[int] = None
    HomeScoreOvertime: Optional[int] = None
    HomeScoreQuarter1: Optional[int] = None
    HomeScoreQuarter2: Optional[int] = None
    HomeScoreQuarter3: Optional[int] = None
    HomeScoreQuarter4: Optional[int] = None
    HomeTeam: Optional[str] = None
    HomeTeamID: Optional[int] = None
    HomeTeamMoneyLine: Optional[int] = None
    HomeTimeouts: Optional[int] = None
    IsInProgress: Optional[bool] = None
    IsOver: Optional[bool] = None
    IsOvertime: Optional[bool] = None
    LastPlay: Optional[str] = None
    LastUpdated: Optional[str] = None
    NeutralVenue: Optional[bool] = None
    OverPayout: Optional[int] = None
    OverUnder: Optional[float] = None
    PointSpread: Optional[float] = None
    PointSpreadAwayTeamMoneyLine: Optional[int] = None
    PointSpreadHomeTeamMoneyLine: Optional[int] = None
    Possession: Optional[str] = None
    Quarter: Optional[str] = None
    QuarterDescription: Optional[str] = None
    RedZone: Optional[str] = None
    RefereeID: Optional[int] = None
    ScoreID: Optional[int] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    StadiumDetails: Optional[Stadium] = None
    StadiumID: Optional[int] = None
    Status: Optional[str] = None
    TimeRemaining: Optional[str] = None
    UnderPayout: Optional[int] = None
    Week: Optional[int] = None
    YardLine: Optional[int] = None
    YardLineTerritory: Optional[str] = None


class FieldFormatGameStatsSeasonGetResponse(RootModel[List[Game]]):
    root: List[Game]


class FieldFormatGameStatsByWeekSeasonWeekGetResponse(RootModel[List[Game]]):
    root: List[Game]


class FieldFormatSchedulesSeasonGetResponse(RootModel[List[Schedule]]):
    root: List[Schedule]


class FieldFormatScoresSeasonGetResponse(RootModel[List[Score]]):
    root: List[Score]


class FieldFormatScoresByDateDateGetResponse(RootModel[List[Score]]):
    root: List[Score]


class FieldFormatScoresByWeekSeasonWeekGetResponse(RootModel[List[Score]]):
    root: List[Score]


class FieldFormatSimulatedScoresNumberofplaysGetResponse(RootModel[List[Score]]):
    root: List[Score]


class PlayerDetail(BaseModel):
    Active: Optional[bool] = None
    Age: Optional[int] = None
    AverageDraftPosition: Optional[float] = None
    BirthDate: Optional[str] = None
    BirthDateString: Optional[str] = None
    ByeWeek: Optional[int] = None
    College: Optional[str] = None
    CollegeDraftPick: Optional[int] = None
    CollegeDraftRound: Optional[int] = None
    CollegeDraftTeam: Optional[str] = None
    CollegeDraftYear: Optional[int] = None
    CurrentStatus: Optional[str] = None
    CurrentTeam: Optional[str] = None
    DeclaredInactive: Optional[bool] = None
    DepthDisplayOrder: Optional[int] = None
    DepthOrder: Optional[int] = None
    DepthPosition: Optional[str] = None
    DepthPositionCategory: Optional[str] = None
    DraftKingsName: Optional[str] = None
    DraftKingsPlayerID: Optional[int] = None
    Experience: Optional[int] = None
    ExperienceString: Optional[str] = None
    FanDuelName: Optional[str] = None
    FanDuelPlayerID: Optional[int] = None
    FantasyAlarmPlayerID: Optional[int] = None
    FantasyDraftName: Optional[str] = None
    FantasyDraftPlayerID: Optional[int] = None
    FantasyPosition: Optional[str] = None
    FantasyPositionDepthOrder: Optional[int] = None
    FirstName: Optional[str] = None
    GlobalTeamID: Optional[int] = None
    Height: Optional[str] = None
    HeightFeet: Optional[int] = None
    HeightInches: Optional[int] = None
    InjuryBodyPart: Optional[str] = None
    InjuryNotes: Optional[str] = None
    InjuryPractice: Optional[str] = None
    InjuryPracticeDescription: Optional[str] = None
    InjuryStartDate: Optional[str] = None
    InjuryStatus: Optional[str] = None
    IsUndraftedFreeAgent: Optional[bool] = None
    LastName: Optional[str] = None
    LatestNews: Optional[List[News]] = None
    Name: Optional[str] = None
    Number: Optional[int] = None
    PhotoUrl: Optional[str] = None
    PlayerID: Optional[int] = None
    PlayerSeason_1: Optional[PlayerSeason] = Field(None, alias='PlayerSeason')
    Position: Optional[str] = None
    PositionCategory: Optional[str] = None
    RotoWirePlayerID: Optional[int] = None
    RotoworldPlayerID: Optional[int] = None
    ShortName: Optional[str] = None
    SportRadarPlayerID: Optional[str] = None
    SportsDirectPlayerID: Optional[int] = None
    StatsPlayerID: Optional[int] = None
    Status: Optional[str] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    UpcomingDraftKingsSalary: Optional[int] = None
    UpcomingFanDuelSalary: Optional[int] = None
    UpcomingGameOpponent: Optional[str] = None
    UpcomingGameWeek: Optional[int] = None
    UpcomingOpponentPositionRank: Optional[int] = None
    UpcomingOpponentRank: Optional[int] = None
    UpcomingSalary: Optional[int] = None
    UpcomingYahooSalary: Optional[int] = None
    UsaTodayHeadshotNoBackgroundUpdated: Optional[str] = None
    UsaTodayHeadshotNoBackgroundUrl: Optional[str] = None
    UsaTodayHeadshotUpdated: Optional[str] = None
    UsaTodayHeadshotUrl: Optional[str] = None
    UsaTodayPlayerID: Optional[int] = None
    Weight: Optional[int] = None
    XmlTeamPlayerID: Optional[int] = None
    YahooName: Optional[str] = None
    YahooPlayerID: Optional[int] = None


class FieldFormatPlayersTeamGetResponse(RootModel[List[PlayerDetail]]):
    root: List[PlayerDetail]
